"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--r2i(9o1^qmfun!t%yci+ga0!m1b!q+j-s-kex*#3as_1m#9!5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0','*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'corsheaders',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage',
    'core'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add at the top
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # For development/testing

# OR for production (recommended):
CORS_ALLOWED_ORIGINS = [
    "https://your-project-id.web.app",
    "https://your-project-id.firebaseapp.com",
    "https://yourdomain.com",  # Your GoDaddy domain when you set it up
]

# Required for Django admin (and any POST) when accessed via HTTPS on Render
CSRF_TRUSTED_ORIGINS = [
    "https://du-backend-dj.onrender.com",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# If using cookies/sessions:
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL")
        )
}

# Neither channels_redis nor django-redis caps its connection pool size by
# default — under load they'll keep opening new Redis connections rather
# than reusing a bounded set, which is how a small managed-Redis plan's
# connection limit gets exhausted even with a modest number of active users.
# These caps force reuse instead. Tune via env vars if the plan's limit
# changes; keep (channel layer max) + (cache max) comfortably under whatever
# your Redis plan's total connection limit is.
REDIS_CHANNEL_MAX_CONNECTIONS = int(os.getenv("REDIS_CHANNEL_MAX_CONNECTIONS", "15"))
REDIS_CACHE_MAX_CONNECTIONS = int(os.getenv("REDIS_CACHE_MAX_CONNECTIONS", "10"))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
                "max_connections": REDIS_CHANNEL_MAX_CONNECTIONS,
            }],
        },
    },
}

# Same Redis instance/DB as the channel layer above — many managed Redis
# offerings (e.g. Redis Cloud fixed/free plans) only expose a single logical
# DB, so a separate DB index isn't reliably available. A KEY_PREFIX keeps
# cache keys from ever colliding with channels_redis's own "asgi:"-prefixed
# pub/sub keys in that shared keyspace. Set CACHE_REDIS_URL to point at a
# different instance/DB if one becomes available.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("CACHE_REDIS_URL", os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")),
        "KEY_PREFIX": "du_cache",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": REDIS_CACHE_MAX_CONNECTIONS},
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ── Cloudinary (media / file uploads) ────────────────────────────────────────
# Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET in env.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY':    os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}
DEFAULT_FILE_STORAGE = 'core.storage.AutoCloudinaryStorage'

MEDIA_URL = '/media/'   # kept for local fallback / admin compatibility
MEDIA_ROOT = BASE_DIR / "media"

# Max upload size: 50 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# Web Push (VAPID)
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
VAPID_SUBJECT = os.getenv("VAPID_SUBJECT", "mailto:admin@example.com")

# Bunny.net Stream (video delivery)
BUNNY_STREAM_API_KEY = os.getenv("BUNNY_STREAM_API_KEY", "")
BUNNY_STREAM_LIBRARY_ID = os.getenv("BUNNY_STREAM_LIBRARY_ID", "")
BUNNY_STREAM_CDN_HOSTNAME = os.getenv("BUNNY_STREAM_CDN_HOSTNAME", "")  # e.g. vz-abc123.b-cdn.net
BUNNY_STREAM_TOKEN_KEY = os.getenv("BUNNY_STREAM_TOKEN_KEY", "")        # token auth key from Bunny dashboard

# GIPHY (chat GIF picker) — get a key at developers.giphy.com
GIPHY_API_KEY = os.getenv("GIPHY_API_KEY", "")

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'