"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--r2i(9o1^qmfun!t%yci+ga0!m1b!q+j-s-kex*#3as_1m#9!5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0','*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'corsheaders',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage',
    'core'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add at the top
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # For development/testing

# OR for production (recommended):
CORS_ALLOWED_ORIGINS = [
    "https://your-project-id.web.app",
    "https://your-project-id.firebaseapp.com",
    "https://yourdomain.com",  # Your GoDaddy domain when you set it up
]

# Required for Django admin (and any POST) when accessed via HTTPS on Render
CSRF_TRUSTED_ORIGINS = [
    "https://du-backend-dj.onrender.com",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# If using cookies/sessions:
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            # Without this, CONN_MAX_AGE defaults to 0 and every request/websocket
            # message opens a brand-new Postgres connection, which can spike past
            # the plan's max_connections under concurrent chat load. Reusing
            # connections for this long keeps connection churn low.
            conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "60")),
        )
}

# Neither channels_redis nor django-redis caps its connection pool size by
# default — under load they'll keep opening new Redis connections rather
# than reusing a bounded set, which is how a small managed-Redis plan's
# connection limit gets exhausted even with a modest number of active users.
# These caps force reuse instead. Tune via env vars if the plan's limit
# changes; keep (channel layer max) + (cache max) comfortably under whatever
# your Redis plan's total connection limit is.
#
# 2026-07-14: moved to a 250MB Redis Cloud plan in the same region as the
# backend (Singapore) — real limits are 256 connections and 1000 ops/sec
# (up from the free/30MB tier's 30 connections and 100 ops/sec that caused
# the original crash). Sized well under the new ceiling on purpose: at
# <300 users there's no need to fill the pool close to its limit, so
# 60+20=80 (~31% of 256) leaves generous headroom for growth rather than
# just matching what the plan allows.
REDIS_CHANNEL_MAX_CONNECTIONS = int(os.getenv("REDIS_CHANNEL_MAX_CONNECTIONS", "60"))
REDIS_CACHE_MAX_CONNECTIONS = int(os.getenv("REDIS_CACHE_MAX_CONNECTIONS", "20"))

# Chat's per-message inbox fanout (one group_send per other room member, see
# ChatConsumer._fanout_inbox_updates and ChatRoomMessages.post) is bounded to
# this many concurrent group_send calls so a large room can't burst past
# REDIS_CHANNEL_MAX_CONNECTIONS or the plan's ops/sec cap in one shot — keep
# comfortably below the channel pool size to leave headroom for the room
# broadcast itself and any other concurrent chat activity in the process.
CHAT_FANOUT_CONCURRENCY = int(os.getenv("CHAT_FANOUT_CONCURRENCY", "20"))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
                "max_connections": REDIS_CHANNEL_MAX_CONNECTIONS,
            }],
        },
    },
}

# Same Redis instance/DB as the channel layer above — many managed Redis
# offerings (e.g. Redis Cloud fixed/free plans) only expose a single logical
# DB, so a separate DB index isn't reliably available. A KEY_PREFIX keeps
# cache keys from ever colliding with channels_redis's own "asgi:"-prefixed
# pub/sub keys in that shared keyspace. Set CACHE_REDIS_URL to point at a
# different instance/DB if one becomes available.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("CACHE_REDIS_URL", os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")),
        "KEY_PREFIX": "du_cache",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": REDIS_CACHE_MAX_CONNECTIONS},
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ── Cloudinary (legacy media storage — old uploads only) ─────────────────────
# No longer the active storage backend (see R2 below) — its free tier ran
# out. Kept configured only so already-uploaded ChatMessage.attachment_url /
# Sticker.image_url / ChatRoom.image_url values (absolute URLs stored at
# upload time) keep resolving; the account must stay active until that old
# media naturally ages out or is separately migrated.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY':    os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# ── Cloudflare R2 (media storage — chat attachments, avatars, stickers) ──────
# Active storage backend for all new uploads. R2 is S3-API-compatible (hence
# django-storages' S3Boto3Storage) and charges zero egress fees, unlike
# Cloudinary's bundled storage+bandwidth credit model.
# Create a bucket + API token in the Cloudflare dashboard, then set these env
# vars (locally via .env, on Render via the dashboard's env var settings):
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID") or None
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY") or None
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME") or None
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL") or None  # https://<account_id>.r2.cloudflarestorage.com
R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL") or None      # custom domain or <bucket>.<account_id>.r2.dev
# botocore hard-crashes (ValueError: Invalid endpoint) on an empty-string
# endpoint/bucket rather than treating it like "unset" — `or None` above
# keeps local/test environments without R2 credentials configured from
# blowing up the moment anything calls default_storage.save()/url().

AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL
# django-storages builds delivery URLs as "<url_protocol>//<CUSTOM_DOMAIN>/<path>"
# — it expects a bare hostname, NOT a full URL. Cloudflare's dashboard shows
# the public URL with an "https://" prefix already on it, which is exactly
# what someone would naturally copy-paste into the env var; strip it here so
# a scheme-included value doesn't silently produce a broken
# "https://https://pub-xxxx.r2.dev/..." URL for every single upload.
AWS_S3_CUSTOM_DOMAIN = (
    R2_PUBLIC_URL.split("://", 1)[-1].rstrip("/") if R2_PUBLIC_URL else None
)
AWS_S3_REGION_NAME = "auto"  # required by R2's S3-compatible API
AWS_DEFAULT_ACL = None       # R2 doesn't support S3 ACLs
AWS_QUERYSTRING_AUTH = False  # bucket is served publicly via AWS_S3_CUSTOM_DOMAIN, no signed URLs
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_S3_FILE_OVERWRITE = False

# Without this, R2 sends no Cache-Control header at all, so the browser
# re-downloads the full file (attachment, avatar, thumbnail) from scratch on
# every single view instead of ever using its own cache — confirmed via a
# live Network tab check (repeated 200s at full size, not disk-cache hits).
# Safe to cache aggressively since AWS_S3_FILE_OVERWRITE=False means a given
# URL's content never changes after upload — there's no staleness risk to
# guard against with a shorter TTL.
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "public, max-age=31536000, immutable",
}

DEFAULT_FILE_STORAGE = 'core.storage.R2Storage'

MEDIA_URL = '/media/'   # kept for local fallback / admin compatibility
MEDIA_ROOT = BASE_DIR / "media"

# Max upload size: 50 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# Web Push (VAPID)
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
VAPID_SUBJECT = os.getenv("VAPID_SUBJECT", "mailto:admin@example.com")

# Bunny.net Stream (video delivery)
BUNNY_STREAM_API_KEY = os.getenv("BUNNY_STREAM_API_KEY", "")
BUNNY_STREAM_LIBRARY_ID = os.getenv("BUNNY_STREAM_LIBRARY_ID", "")
BUNNY_STREAM_CDN_HOSTNAME = os.getenv("BUNNY_STREAM_CDN_HOSTNAME", "")  # e.g. vz-abc123.b-cdn.net
BUNNY_STREAM_TOKEN_KEY = os.getenv("BUNNY_STREAM_TOKEN_KEY", "")        # token auth key from Bunny dashboard

# Bunny.net account-level API key (My Account → API on the Bunny dashboard) —
# distinct from BUNNY_STREAM_API_KEY above, which is scoped to one Stream
# library and cannot call account-level endpoints like Purge Cache.
BUNNY_ACCOUNT_API_KEY = os.getenv("BUNNY_ACCOUNT_API_KEY", "")

# GIPHY (chat GIF picker) — get a key at developers.giphy.com
GIPHY_API_KEY = os.getenv("GIPHY_API_KEY", "")

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'