# Generated by Django 6.0 on 2026-01-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ir',
            fields=[
                ('ir_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('ir_name', models.CharField(max_length=45)),
                ('ir_email', models.EmailField(max_length=254, unique=True)),
                ('ir_access_level', models.PositiveSmallIntegerField(default=5)),
                ('ir_password', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('plan_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('weekly_info_target', models.IntegerField(default=0)),
                ('weekly_plan_target', models.IntegerField(default=0)),
                ('weekly_uv_target', models.IntegerField(blank=True, null=True)),
                ('started_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrId',
            fields=[
                ('ir_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekly_info_done', models.IntegerField(default=0)),
                ('weekly_plan_done', models.IntegerField(default=0)),
                ('weekly_info_target', models.IntegerField(default=0)),
                ('weekly_plan_target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InfoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(max_length=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('info_name', models.CharField(max_length=100)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ir')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateTimeField(auto_now_add=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ir')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField()),
                ('weekly_info_done', models.IntegerField(default=0)),
                ('weekly_plan_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LDC', 'LDC'), ('LS', 'LS'), ('GC', 'GC'), ('IR', 'IR')], max_length=10)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ir')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'unique_together': {('team', 'ir')},
            },
        ),
    ]
