# Generated by Django 6.0 on 2026-01-01 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='dr_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ir',
            name='name_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infodetail',
            name='info_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infodetail',
            name='response',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ir',
            name='ir_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='plan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('LDC', 'Ldc'), ('LS', 'Ls'), ('GC', 'Gc'), ('IR', 'Ir')], max_length=5),
        ),
    ]
