# Generated by Django 5.0 on 2026-01-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_infodetail_id_alter_plandetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='uv_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WeeklyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('week_start', models.DateTimeField()),
                ('week_end', models.DateTimeField()),
                ('ir_weekly_info_target', models.IntegerField(blank=True, null=True)),
                ('ir_weekly_plan_target', models.IntegerField(blank=True, null=True)),
                ('ir_weekly_uv_target', models.IntegerField(blank=True, null=True)),
                ('team_weekly_info_target', models.IntegerField(blank=True, null=True)),
                ('team_weekly_plan_target', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ir')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'indexes': [models.Index(fields=['week_number', 'year'], name='core_weekly_week_nu_d1d12a_idx'), models.Index(fields=['ir', 'week_number', 'year'], name='core_weekly_ir_id_e6f26e_idx'), models.Index(fields=['team', 'week_number', 'year'], name='core_weekly_team_id_1bff81_idx')],
                'unique_together': {('week_number', 'year', 'ir'), ('week_number', 'year', 'team')},
            },
        ),
    ]
