# Generated by Django 5.0 on 2026-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ir_uv_count_weeklytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytarget',
            name='team_weekly_uv_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
