# Generated by Django 5.0 on 2026-01-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weeklytarget_team_weekly_uv_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ir',
            name='hierarchy_path',
            field=models.CharField(db_index=True, default='/', max_length=500),
        ),
        migrations.AddField(
            model_name='ir',
            name='parent_ir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_downlines', to='core.ir'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='core.ir'),
        ),
        migrations.AlterField(
            model_name='infodetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ir',
            name='ir_access_level',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CTC', 'Ctc'), ('LDC', 'Ldc'), ('LS', 'Ls'), ('GC', 'Gc'), ('IR', 'Ir')], max_length=5),
        ),
        migrations.AlterField(
            model_name='teamweek',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklytarget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
