# Generated by Django 5.0 on 2026-01-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ir_hierarchy_level_ir_hierarchy_path_ir_parent_ir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='status',
            field=models.CharField(blank=True, choices=[('closing_pending', 'Closing Pending'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('uvs_on_counter', "UV's on Counter")], default='closing_pending', max_length=20, null=True),
        ),
    ]
