# Generated by Django 5.0 on 2026-01-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plandetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWeeklyTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_targets_json', to='core.team')),
            ],
            options={
                'verbose_name': 'Team Weekly Targets (JSON)',
                'verbose_name_plural': 'Team Weekly Targets (JSON)',
            },
        ),
    ]
