# Generated by Django 5.0 on 2026-01-26 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teamweeklytargets'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uv_count', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ir')),
            ],
        ),
    ]
