# Generated by Django 5.0 on 2026-01-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_uvdetail_prospect_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CTC', 'Ctc'), ('LDC', 'Ldc'), ('LS', 'Ls'), ('GC', 'Gc'), ('IR', 'Ir')], max_length=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='infodetail',
            name='info_type',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Re-info', 'Reinfo')], default='Fresh', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklytarget',
            name='pocket_weekly_info_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklytarget',
            name='pocket_weekly_plan_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklytarget',
            name='pocket_weekly_uv_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pockets', to='core.ir')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to='core.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('week_number', 'year', 'ir'), ('week_number', 'year', 'team')},
        ),
        migrations.AddField(
            model_name='weeklytarget',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_targets', to='core.pocket'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('week_number', 'year', 'ir'), ('week_number', 'year', 'pocket'), ('week_number', 'year', 'team')},
        ),
        migrations.AddIndex(
            model_name='weeklytarget',
            index=models.Index(fields=['pocket', 'week_number', 'year'], name='core_weekly_pocket__b0e468_idx'),
        ),
        migrations.AddField(
            model_name='pocketmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket_members_added', to='core.ir'),
        ),
        migrations.AddField(
            model_name='pocketmember',
            name='ir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket_memberships', to='core.ir'),
        ),
        migrations.AddField(
            model_name='pocketmember',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.pocket'),
        ),
        migrations.AddField(
            model_name='pocketmember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_members', to='core.team'),
        ),
        migrations.AlterUniqueTogether(
            name='pocket',
            unique_together={('team', 'name')},
        ),
        migrations.AddIndex(
            model_name='pocketmember',
            index=models.Index(fields=['pocket', 'role'], name='core_pocket_pocket__65ab3f_idx'),
        ),
        migrations.AddIndex(
            model_name='pocketmember',
            index=models.Index(fields=['ir', 'team'], name='core_pocket_ir_id_d338fb_idx'),
        ),
        migrations.AddIndex(
            model_name='pocketmember',
            index=models.Index(fields=['pocket', 'ir'], name='core_pocket_pocket__63c48a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pocketmember',
            unique_together={('pocket', 'ir')},
        ),
    ]
