# Generated by Django 5.0 on 2026-01-30 05:20
#
# The RemoveConstraint/RemoveIndex/RenameIndex operations originally here only
# made sense against artifacts created by 0013_pockets_and_targets's duplicate
# CreateModel/AddConstraint/AddIndex calls. Since 0013 has been trimmed to a
# no-op (it duplicated 0012, breaking from-scratch migrate), those constraints,
# indexes, and old-names never exist to remove/rename — removed here to match.
# The remaining operations (is_head field, role AlterField, unique_together)
# are real state changes and are kept.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_info_type_and_pocket_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketmember',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pocketmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CTC', 'Ctc'), ('LDC', 'Ldc'), ('LS', 'Ls'), ('GC', 'Gc'), ('IR', 'Ir')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='pocket',
            unique_together={('team', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pocketmember',
            unique_together={('pocket', 'ir')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('week_number', 'year', 'ir'), ('week_number', 'year', 'pocket'), ('week_number', 'year', 'team')},
        ),
    ]
