# Generated by Django 5.0 on 2026-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_info_type_and_pocket_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pocket',
            name='unique_pocket_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='pocketmember',
            name='unique_pocket_member',
        ),
        migrations.RemoveConstraint(
            model_name='weeklytarget',
            name='unique_ir_target',
        ),
        migrations.RemoveConstraint(
            model_name='weeklytarget',
            name='unique_team_target',
        ),
        migrations.RemoveConstraint(
            model_name='weeklytarget',
            name='unique_pocket_target',
        ),
        migrations.RemoveIndex(
            model_name='weeklytarget',
            name='pocket_week_idx',
        ),
        migrations.RenameIndex(
            model_name='pocketmember',
            new_name='core_pocket_pocket__65ab3f_idx',
            old_name='pocket_role_idx',
        ),
        migrations.RenameIndex(
            model_name='pocketmember',
            new_name='core_pocket_ir_id_d338fb_idx',
            old_name='ir_team_idx',
        ),
        migrations.RenameIndex(
            model_name='pocketmember',
            new_name='core_pocket_pocket__63c48a_idx',
            old_name='pocket_ir_idx',
        ),
        migrations.AddField(
            model_name='pocketmember',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pocketmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CTC', 'Ctc'), ('LDC', 'Ldc'), ('LS', 'Ls'), ('GC', 'Gc'), ('IR', 'Ir')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='pocket',
            unique_together={('team', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pocketmember',
            unique_together={('pocket', 'ir')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('week_number', 'year', 'ir'), ('week_number', 'year', 'pocket'), ('week_number', 'year', 'team')},
        ),
    ]
