# Generated by Django 5.0 on 2026-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='core_pushsu_ir_id_b43814_idx',
            old_name='core_pushsu_ir_cddbf9_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('UV_ADDED', 'UV Added'), ('UV_UPDATED', 'UV Updated'), ('PLAN_ADDED', 'Plan Added'), ('PLAN_UPDATED', 'Plan Updated'), ('NEW_IR', 'New IR Registered'), ('TEAM_CREATED', 'Team Created')], max_length=20),
        ),
    ]
