# Generated by Django 5.0 on 2026-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_core_pushsu_ir_cddbf9_idx_core_pushsu_ir_id_b43814_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='fcm_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
