# Generated by Django 5.0 on 2026-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_decimal_uv_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('UV_ADDED', 'UV Added'), ('UV_UPDATED', 'UV Updated'), ('UV_DELETED', 'UV Deleted'), ('PLAN_ADDED', 'Plan Added'), ('PLAN_UPDATED', 'Plan Updated'), ('PLAN_DELETED', 'Plan Deleted'), ('INFO_ADDED', 'Info Added'), ('INFO_UPDATED', 'Info Updated'), ('INFO_DELETED', 'Info Deleted'), ('NEW_IR', 'New IR Registered'), ('IR_DELETED', 'IR Deleted'), ('TEAM_CREATED', 'Team Created')], max_length=20),
        ),
    ]
