# Generated by Django 5.0 on 2026-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_learnvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('no_money', 'No Money'), ('no_mindset', 'No Mindset'), ('timing', 'Timing'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='uv_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='status',
            field=models.CharField(blank=True, choices=[('closing_pending', 'Closing Pending'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('kiv', 'KIV'), ('uvs_on_counter', "UV's on Counter")], default='closing_pending', max_length=20, null=True),
        ),
    ]
