# Generated by Django 5.0 on 2026-06-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_plan_detail_rejection_followup_uv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTabsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_tabs_config', to='core.ir')),
            ],
        ),
        migrations.AddIndex(
            model_name='chattabsconfig',
            index=models.Index(fields=['ir'], name='core_chatta_ir_id_ddb01b_idx'),
        ),
    ]
