# Generated by Django 5.0 on 2026-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_chat_tabs_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bunny_video_id', models.CharField(max_length=100, unique=True)),
                ('bunny_library_id', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Sort order in the list')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dream Video',
                'verbose_name_plural': 'Dream Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatmessagereaction',
            new_name='core_chatme_message_d4ca49_idx',
            old_name='core_chatme_message_emoji_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ir',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
