# Generated by Django 5.0 on 2026-06-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_dreamvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='presented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_presented', to='core.ir'),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='ir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='core.ir'),
        ),
    ]
