# Generated by Django 5.0 on 2026-07-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_plandetail_presented_by_alter_plandetail_ir'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='hide_history_before_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
