# Generated by Django 5.0 on 2026-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_chat_history_visibility_system_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
