# Generated by Django 5.0 on 2026-07-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_ir_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mapping_config', to='core.ir')),
            ],
            options={
                'indexes': [models.Index(fields=['ir'], name='core_dashbo_ir_id_90aec8_idx')],
            },
        ),
    ]
