# Generated by Django 5.0 on 2026-07-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_sticker_packs_and_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='admin_upload',
            field=models.FileField(blank=True, null=True, upload_to='stickers/admin/'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sticker_packs', to='core.ir'),
        ),
        migrations.CreateModel(
            name='StickerPackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_pack_subscriptions', to='core.ir')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.stickerpack')),
            ],
            options={
                'unique_together': {('ir', 'pack')},
            },
        ),
    ]
