# Generated by Django 5.0 on 2026-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sticker_pack_public_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice'), ('sticker', 'Sticker'), ('gif', 'Gif'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
