# Generated by Django 5.0 on 2026-07-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_gif_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('UV_ADDED', 'UV Added'), ('UV_UPDATED', 'UV Updated'), ('UV_DELETED', 'UV Deleted'), ('PLAN_ADDED', 'Plan Added'), ('PLAN_UPDATED', 'Plan Updated'), ('PLAN_DELETED', 'Plan Deleted'), ('INFO_ADDED', 'Info Added'), ('INFO_UPDATED', 'Info Updated'), ('INFO_DELETED', 'Info Deleted'), ('NEW_IR', 'New IR Registered'), ('IR_DELETED', 'IR Deleted'), ('TEAM_CREATED', 'Team Created'), ('MEMBER_ADDED', 'Team Member Added'), ('MEMBER_UPDATED', 'Team Member Updated'), ('MEMBER_DELETED', 'Team Member Deleted'), ('IR_APPROVAL_REQUEST', 'IR Approval Request'), ('IR_REQUEST_REJECTED', 'IR Request Rejected')], max_length=20),
        ),
        migrations.CreateModel(
            name='IrPendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REGISTER', 'Register New IR'), ('DELETE', 'Delete IR')], max_length=10)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('target_ir_code', models.CharField(max_length=18)),
                ('target_ir_name', models.CharField(max_length=45)),
                ('referred_ir_id', models.CharField(blank=True, max_length=18, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_requests_made', to='core.ir')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_requests_reviewed', to='core.ir')),
                ('target_ir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_delete_requests', to='core.ir')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
