# Generated by Django 5.0 on 2026-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='infodetail',
            index=models.Index(fields=['ir', 'info_date'], name='core_infode_ir_id_e49819_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['ir', 'plan_date'], name='core_plande_ir_id_aca991_idx'),
        ),
        migrations.AddIndex(
            model_name='uvdetail',
            index=models.Index(fields=['ir', 'uv_date'], name='core_uvdeta_ir_id_d96e81_idx'),
        ),
    ]
