# Generated by Django 5.0 on 2026-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_infodetail_core_infode_ir_id_e49819_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='status',
            field=models.CharField(blank=True, choices=[('closing_pending', 'Closing Pending'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('kiv', 'KIV'), ('uvs_on_counter', "UV's on Counter"), ('fg', 'FG')], default='closing_pending', max_length=20, null=True),
        ),
    ]
