# Generated by Django 5.0 on 2026-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_plandetail_add_fg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('admin_upload', models.FileField(blank=True, null=True, upload_to='inventory/files/')),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file_size', models.PositiveIntegerField(blank=True, default=0, help_text='Bytes, auto-populated from admin_upload')),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('leadership', 'Leadership (LDC and above)')], default='everyone', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Sort order in the list')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory File',
                'verbose_name_plural': 'Inventory Files',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bunny_video_id', models.CharField(max_length=100, unique=True)),
                ('bunny_library_id', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('leadership', 'Leadership (LDC and above)')], default='everyone', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Sort order in the list')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Video',
                'verbose_name_plural': 'Inventory Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
