# Generated by Django 5.0 on 2026-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_inventoryfile_inventoryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryfile',
            name='visibility',
            field=models.CharField(choices=[('everyone', 'Everyone — Products tab'), ('gc_and_above', 'GC and above — Financial Documents tab'), ('leadership', 'LDC and above — LDC Inventory tab')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryvideo',
            name='visibility',
            field=models.CharField(choices=[('everyone', 'Everyone — Products tab'), ('gc_and_above', 'GC and above — Financial Documents tab'), ('leadership', 'LDC and above — LDC Inventory tab')], default='everyone', max_length=20),
        ),
    ]
