# Generated by Django 5.0 on 2026-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_inventoryfile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamvideo',
            name='category',
            field=models.CharField(choices=[('dream_tick', 'Dream Tick'), ('success_story', 'Success Story')], default='dream_tick', max_length=20),
        ),
    ]
