# Generated by Django 5.0 on 2026-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_dreamvideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentioned',
            field=models.ManyToManyField(blank=True, related_name='chat_mentions', to='core.ir'),
        ),
    ]
