# Generated by Django 5.0 on 2026-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_notification_ir_request_approved_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnvideo',
            name='category',
            field=models.CharField(choices=[('basic_training', 'Basic Training Videos'), ('building_blocks', '8 Basic Building Blocks')], default='basic_training', max_length=20),
        ),
    ]
