# Generated by Django 5.0 on 2026-08-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_learnvideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='plan_mode',
            field=models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('physical', 'Physical')], max_length=10, null=True),
        ),
    ]
