# Generated by Django 5.0 on 2026-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_plandetail_plan_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnvideo',
            name='category',
            field=models.CharField(choices=[('basic_training', 'Basic Training Videos'), ('building_blocks', 'Basic Building Blocks'), ('growth_bites', 'Growth Bites')], default='basic_training', max_length=20),
        ),
    ]
