# Generated by Django 5.0 on 2026-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_learnvideo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnvideo',
            name='category',
            field=models.CharField(choices=[('basic_training', 'Basic Training Videos'), ('building_blocks', 'Basic Building Blocks'), ('growth_bites', 'Growth Bites'), ('master_networker', 'Master Networker')], default='basic_training', max_length=20),
        ),
    ]
